### PR TITLE
Add keysWith and toListWith

### LINKED ISSUE #105: `keys` and kind erasure
Consider the type of `keys`:
```
keys :: TypeRepMap f -> [SomeTypeRep]
```
this looks fine until you consider the kinds:
```
keys :: forall k (f :: k -> Type). TypeRepMap f -> [SomeTypeRep]
```
the value of `k` is erased! We can try to get it back by patching on `SomeTypeRep` and getting `rep :: TypeRep (a' :: k')` and `typeRepKind rep:: TypeRep k'`, then we could try to `testEquality`, but that requires an extra Typeable constraint on the k, which isn't actually anywhere to be found if say the map is empty.

### PR DESCRIPTION
**Pull request by mniip**
closes #105

### CODE REVIEW

**Comment by mniip** [comment]
`keys` is missing tests. Should I come up with some?

**Review by int-index — APPROVED** [review]

**Comment by int-index** [comment]
The code looks good, but tests are always welcome. Thanks!

**Review by int-index — APPROVED** [review]

**Comment by int-index** [comment]
Looks like I don’t have merge permissions. In this case, @chshersh @vrom911 would you take a look at this patch, please?

**Review by vrom911 — APPROVED** [review]
Thanks!

**Pull request merged**
